### ISSUE TITLE
Initial Equations

### ISSUE THREAD

**Issue by birds-arnt-real** [cusdt-LINK/kcc-flashswap-arb#7]
Are you deriving your initial equations for deltaA1 and deltaA2 from the uni swap CFMM equation aka 

(x-deltaA1)(y+deltab1)=k?

Edit: apologies, I am a clown.

**Comment by gweidart** [comment]
> Are you deriving your initial equations for deltaA1 and deltaA2 from the uni swap CFMM equation aka 
> 
> 
> 
> (x-deltaA1)(y+deltab1)=k?
> 
> 
> 
> Edit: apologies, I am a clown.
> 
> 

No worries 😂
